---
- hosts: build_host
  gather_facts: no
  tasks:
    - name: create build directory
      file:
        path: ~/kursofa/sql-scrpt
        state: directory
        owner: dmytro_bidnyk_itis_2018
        group: root
        mode: '0755'
    - name: copy Dockerfile
      copy:
        src: ./Dockerfile
        dest: ~/kursofa
        owner: dmytro_bidnyk_itis_2018
        group: root
        mode: '0644'
   - name: copy script
        copy:
        src: ./sql-script
        dest: ~/kursofa
        owner: dmytro_bidnyk_itis_2018
        group: root
        mode: '0644'
    - name: build container image
      docker_image:
        name: democontainer:v1.0
        build:
          path: ~/kursofa/Dockerfile
          source: build
        state: present
